# @format

name: Node.js CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # Install dependencies
      - run: npm ci

      # Download .env file
      - name: Download .env file
        uses: actions/download-artifact@v3
        with:
          name: env-file

      # Run test cases
      - name: Run tests
        run: npm test -- --timeout 5000
