# @format

name: Node.js CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # Install dependencies
      - run: npm ci

        # Debug environment variables
      - name: Debug environment variables
        run: |
          echo "DB_URL=$DB_URL"
          echo "PORT=$PORT"
          echo "SECRET_KEY=$SECRET_KEY"

      # Run test cases with environment variables passed
      - name: Run tests
        run: npm test -- --timeout 5000
        env:
          DB_URL: ${{ secrets.DB_URL }}
          PORT: ${{ secrets.PORT }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
