# @format

name: Node.js CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # Set up environment variables
      - name: Set up .env file
        run: |
          echo "DB_URL=${{ secrets.DB_URL }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env

      # Debug step to print .env file content
      - name: Debug environment variables
        run: cat .env

      # Install dependencies
      - run: npm ci

      # Run test cases
      - run: npm test
